rules:
  comma-dangle:
    - 0
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-empty:
    - 0
  no-unused-vars:
    - 2
    - args: all
      argsIgnorePattern: ^_

env:
  browser: true
  es6: true

globals:
  define: true
  chrome: true
  zip: true
  Vue: true
  CodeMirror: true

extends: 'eslint:recommended'
