name: Release

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - name: Prepare
        run: yarn && node scripts/action-helper.js
      - name: Build
        run: |
          yarn build
          cd dist && zip -r ../$RELEASE_PREFIX-webext-v$VERSION.zip . && cd ..

          # Same as `yarn build:selfHosted` but only manifest is changed for now
          TARGET=selfHosted npx gulp manifest
          cd dist && zip -r ../$RELEASE_PREFIX-webext-ffself-v$VERSION.zip . && cd ..
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          params=("-m" "$RELEASE_NAME" "-m" "$RELEASE_NOTE")
          if [ "$PRERELEASE" = "true" ]; then
            params+=("-p")
          fi
          for asset in ./*.zip; do
            params+=("-a" "$asset")
          done
          hub release create "${params[@]}" v$VERSION
